### ISSUE TITLE
craft 3 support

### ISSUE THREAD

**Issue by keithmancuso** [engram-design/FeedMe-Helpers#5]
I assume this is in the works but i wanted to see what the plans were for migrating these to craft 3?  Specifically im wondering about smart map as we use that with feed me all the time

Loving the new feedme by the way, really really works great

**Comment by engram-design** [comment]
@keithmancuso For sure, it may very well be the case these are supported natively as well. We'll keep you posted!

**Comment by shornuk** [comment]
Hi Josh, you kindly created the simplemap helper for V2. Is there any chance of getting that ported to Feedme for C3? Got a big import with map data to do and it’s the only thing holding me back at the moment.

**Comment by engram-design** [comment]
Working on these as quick as we can, and can expect them in the next month, aligning with Feed Me being out of beta.

**Comment by engram-design** [comment]
All current helpers are included in Feed Me [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23) for Craft 3.

@shornuk Regarding Simple Map, the work is done, but there's an issue with the plugin that needs to be fixed. Essentially, its these lines:
https://github.com/ethercreative/simplemap/blob/v3/src/services/MapService.php#L159-L162
That overwrite the element (the owner entry's) content unless its a direct post request, which in this case, its not. Therefore, that code will create a blank, empty model rather than the populated one setup by Feed Me.

Note this function is called via `$owner->getFieldValue($field->handle);` in `saveField()`, which attempts to normalise the field value.

I may make this an issue on their repository.

**Comment by shornuk** [comment]
Thanks for this. If I remember correctly you did a pull request last time round to add compatibility in Simplemap. Is this likely to be the same thing that needs updating?

**Comment by engram-design** [comment]
@shornuk Nah, that was where I was going to have each respective plugin add support to Feed Me on _their_ end, but that never really took off. The work is done in Feed Me, but need to chat with the developers on where to go from here.
